spring.application.name=project1
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:86bb73ff-0811-4bf2-bb1b-9e81df4c739a
spring.datasource.username=ashish
spring.datasource.password=ashish